# Copyright (c) 2025, NVIDIA CORPORATION.

context:
  version: 0.1.0

package:
  name: rapids-logger
  version: ${{ version }}

source:
  path: ../../..

build:
  number: ${{ GIT_DESCRIBE_NUMBER }}
  string: build_${{ GIT_DESCRIBE_HASH }}_${{ GIT_DESCRIBE_NUMBER }}
  script: |
    cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_SHARED_LIBS=ON
    cmake --build build/
    # Run tests from the build directory since they're cheap.
    ctest --test-dir build/
    cmake --install build/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake ${{ cmake_version }}
    - ninja
    - git

tests:
  - script: |
      cmake -S tests/ -B build -GNinja -DCMAKE_BUILD_TYPE=Release
      cmake --build build/
      ctest --test-dir build/

    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake ${{ cmake_version }}
        - ninja
        - git

    files:
      source:
        - tests/
        - rapids_config.cmake
        - VERSION

about:
  homepage: https://rapids.ai/
  repository: https://github.com/rapidsai/rapids-logger
  license: Apache-2.0
  license_file: LICENSE
  summary: Logging framework for RAPIDS built around spdlog
